callmail_project/api/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import patterns, include, url

from .views import RegistrationView, PhoneNumberValidateView, MailView, LoginView, MailForwardView, UserProfileCreateView, CountryCreateView, ForgetPassword, ResetPassword, DeleteEmailLink, ChangePassword, AdvertismentBanner,PhoneNumberForgetPasswordValidateView

urlpatterns = patterns('',
                       url(r'^docs/', include('rest_framework_swagger.urls')),
                       url(r'^auth/', LoginView.as_view(), name='login'),
                       url(r'^register/$', RegistrationView.as_view(), name='user_registration'),
                       url(r'^validate-phone/$', PhoneNumberValidateView.as_view(), name='validate_phone'),
                       url(r'^validate-forget/$', PhoneNumberForgetPasswordValidateView.as_view(), name='validate_forget'),
                       url(r'^mail/$', MailView.as_view(), name='mail'),
                       url(r'^mail-forward/$', MailForwardView.as_view(), name='mail_forward'),
                       url(r'^mail-forward-destroy/$', DeleteEmailLink.as_view(), name='mail_forward_destroy'),
                       url(r'^user-profile/$', UserProfileCreateView.as_view(), name='user_profile_create'),
                       url(r'^country-code/$', CountryCreateView.as_view(), name='country_code'),
                       url(r'^forgot-password/$', ForgetPassword.as_view(), name='forgot_password'),
                       url(r'^forgot-password/(?P<secret_token>.+)/$', ResetPassword.as_view(), name='reset_password'),
                       url(r'^change-password/$', ChangePassword.as_view(), name='change_password'),
                       url(r'^ads/$', AdvertismentBanner.as_view(), name='banner'),





)

callmail_project/media/attachments/models.py
import os

from django.db import models
from django.contrib.auth.models import User


class Mail(models.Model):
    user = models.ForeignKey(User)
    from_user = models.EmailField()
    to_user = models.EmailField()
    subject = models.CharField(max_length=255, blank=True, null=True)
    body = models.TextField(blank=True, null=True)
    date_email = models.DateTimeField()


    def __unicode__(self):
        return 'From: %s To: %s' %(self.from_user, self.to_user)



class MailAttachment(models.Model):
    mail = models.ForeignKey(Mail)
    attachment = models.FileField(upload_to='attachments/')

    def __unicode__(self):
        return "%s's mail attachment" %(self.mail.user)

    def filename(self):
        return os.path.basename(self.attachment.name)

callmail_project/templates/about.html
{% extends 'base.html' %}
{% block head_content %}
<div class="height_100"></div>
{% endblock head_content %}
{% block content %}
<section id="main_content" class="bg_gray">
    <div class="container">
        <div class="sec_up">
            <div class="row alter">
                <div class="col-sm-8 col-md-9">
                    <div class="content">
                        <div class="about_us">
                            <div class="page_title">
                                <h1>About Us</h1>


                            </div>
                            <!-- /page_title -->

                            <div class="row_block">
                                <h3>What is CallnMail?</h3>

                                <p>CallnMail is an email forwarding facility, acting through a website on the internet, as well as

providing its services through mobile applications.</p>
                            </div>

                            <div class="row_block">
                                <h3>Why use CallnMail?</h3>

                                <p>If you are a mobile phone user, you can register your mobile number with the CallnMail.com

service, which in turn allows other CallnMail users and friends to email you, without knowing

your personal or professional email id; all they need is your mobile number.

In addition, when people are contacting you by phone, you can give out your email ID as the

CallnMail.com email; using that specific mobile phone number, they contacted you from.

CALLNMAIL is an email forwarding service that provides its services through mobile

applications based on using the verified mobile number as an email id to forward email

messages.

Find any person by just knowing their mobile number. Users provide a valid email address ,

and a valid mobile number , CALLNMAIL verifies both and gives the option to the user to

start using its features in order to forward all incoming email sent to the email country code

(with “+”) followed by the mobile number under the domain CALLNMAIL   (example

+44mobilenumber@CallnMail.com ) is a mobile number from the UK.</p>
                            </div>

                            <div class="row_block">
                                <h3>Who</h3>

                                <p>CallnMail is founded and owned by TASMEEM UNITED CO WLL.</p>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- /content -->

                <div class="col-sm-4 col-md-3">
                    {% include 'sidebar.html' %}
                </div>
                <!-- /sidebar -->
            </div>
        </div>
    </div>
</section>
{% endblock %}

callmail_project/templates/activate_account.html
{% extends 'base.html' %}
{% load static %}
{% block extra_css %}
	<link rel="stylesheet" type="text/css" href="{% static 'css/fuzzyDropdown.css' %}">
{% endblock extra_css %}
{% block extra_js %}
<script type="text/javascript" src="{% static 'js/fuse.min.js' %}"></script>
	<script type="text/javascript" src="{% static 'js/fuzzyDropdown.js' %}"></script>
{% endblock extra_js %}
{% block content %}
    <section id="main_content" class="registration bg_gray">
			<div class="container">
				<div class="page_title">
					<h1>Create an account or sign in</h1>
					<p>Use your phone number for the email address <br>and link it to your existing email.</p>
				</div><!-- /page_title -->
			</div>

			<div class="sec_reg">
				<div class="container">
					<div class="row">
						<div class="col-sm-12">
							<div class="tab_panel" role="tabpanel">
								<ul class="nav nav-tabs" role="tablist">
									<li role="presentation" class="active"><a href="{% url 'mail:activate_user' %}" aria-controls="activate_account" role="tab" data-toggle="tab">Activate Account</a></li>
								</ul>

								<div class="box_container">
									<div class="tab-content">
										<div role="tabpanel" class="tab-pane active" id="activate_account">
											<div class="tab_item_content active_account">
												<div class="content_logo"><a href="#"><img src="{% static 'images/content_logo_bg.png' %}" alt="logo"></a></div>

												<div class="reg_content">
													<form action="" method="post">
                                                        {% csrf_token %}
														<div class="form-group">
															<div class="active_code">
                                                                {{ form.activation_code }}
																<a class="input_add_on" href="#"><i class="fa fa-lock"></i></a>

															</div>
														</div>
                                                        <p>{{ error }}</p>
														<button type="submit" class="button">Activate My Account</button>
													</form>


												</div><!-- /reg_content -->
											</div>
										</div><!-- /tab_item_content -->
									</div>

									<span class="reg_ribbon"><img src="{% static 'images/ribbon.png' %}" alt="ribbon"></span>
									<span class="iphone_6"><img src="{% static 'images/iphone_6.png' %}" alt="iphone-6"></span>
								</div><!-- /box_container -->
							</div>
						</div>
					</div><!-- /row -->

					<div class="row">

						<div class="col-sm-12">
							<div class="app_store">
								<a href="https://itunes.apple.com/au/app/callnmail/id1023138715?mt=8"><img src="{% static 'images/icon_app_store.png' %}" alt="app_store"></a>
								<a href="https://play.google.com/store/apps/details?id=com.callnmail&hl=en"><img src="{% static 'images/icon_app_google_play.png' %}" alt="google_play"></a>
							</div>
						</div>
					</div><!-- /row -->
				</div>
			</div>
		</section>
{% endblock %}

callmail_project/templates/change_password.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <section id="main_content"
             class="sec_profile">
        <div class="container">
            <div class="box_container">
                <form action=""
                      method="post">
                    {% csrf_token %}
                    <div class="row">
                        <div class="col-md-4 col-sm-5">
                            {% include 'profile_part.html' %}
                        </div>
                        <!-- /p_content -->
                        <div class="col-md-8 col-sm-7">
                            <div class="change_pass">
                                <div class="sec_title"><h2>Change Password</h2></div>

                                <div class="p_content sec_half_left">
                                    <p class="text-warning">{{ error }}</p>

                                    <p class="text-warning">{{ form.non_field_errors }}</p>

                                    <div class="custom_input_row">
                                        {{ form.old_password }}
                                        <p class="text-warning">{{ form.old_password.errors }}</p>
                                    </div>
                                    <!-- /custom_input_row -->
                                    <div class="custom_input_row">
                                        {{ form.new_password1 }}
                                        <p class="text-warning">{{ form.new_password1.errors }}</p>
                                    </div>
                                    <!-- /custom_input_row -->
                                    <div class="custom_input_row">
                                        {{ form.new_password2 }}
                                        <p class="text-warning">{{ form.new_password2.errors }}</p>
                                    </div>
                                    <!-- /custom_input_row -->
                                </div>
                                <!-- /p_content -->

                                <div class="p_content sec_half_right">
                                    <div class="edit_panel">
                                        <button class="button"
                                                type="submit">Change Password
                                        </button><br><br>
                                        <a class="button"
                                           href="{% url 'mail:profile' %}">< Back to Profile</a>
                                    </div>
                                </div>
                                <!-- /p_content -->
                            </div>
                            <!-- /change_pass -->
                        </div>
                    </div>
                </form>
            </div>

            <div class="row">
                <div class="col-sm-12">
                    <div class="app_store">
                        <a href="https://itunes.apple.com/au/app/callnmail/id1023138715?mt=8"><img src="{% static 'images/icon_app_store.png' %}"
                                         alt="app_store"></a>
                        <a href="https://play.google.com/store/apps/details?id=com.callnmail&hl=en"><img src="{% static 'images/icon_app_google_play.png' %}"
                                         alt="google_play"></a>
                    </div>
                </div>
            </div>
        </div>
    </section>
{% endblock %}

callmail_project/templates/contact.html
{% extends 'base.html' %}
{% load static %}
{% load bootstrap3 %}
{% block head_content %}
<div class="height_100"></div>
{% endblock head_content %}
{% block content %}

<style type="text/css">
    label {
        display: none;
    }
</style>
<section id="main_content" class="bg_gray contact">
			<div class="container">
				<div class="sec_up">
					<div class="row alter">
						<div class="col-sm-8 col-md-9">
							<div class="content">
								<div class="contact_top">
									<div class="page_title">
										<h1>Contact</h1>
										<p>Please use the contact form on the right side if you have any questions or requests, concerning our services.</p>
									</div><!-- /page_title -->
								</div>
                                   <div class="text-center">{% bootstrap_messages FIXTHIS %}</div>
								<div class="row_block bg_gray">
									<div class="contact_us">
										<div class="row">
											<div class="col-md-8">
												<div class="contact_form">
													<form action="" method="post">
                                                        {% csrf_token %}
														<div class="form-group">
                                                            {{ form }}
															<div class="cf_btn_group">
																<button type="reset" class="button reset">Reset</button>
																<button type="submit" class="button">Submit</button>
															</div>
														</div>
													</form>
												</div>
											</div>
											<div class="col-md-4">
												<div class="contact_info">
													<div class="row_block">
														<p><span class="add_title">Contact Details </span><br>
															Please feel free to contact us:</br>

<a href="mailto:contact@CallnMail.com">contact@CallnMail.com</a>


</p>													</div>
													<div class="row_block">
														<p><span class="add_title">Corprate address </span><br> Tasmeem United CO.  W.L.L<br> Qebla-Souk Aqarat Alkuwait Complex<br> Sixth Floor-office N.633A<br> P.O Box: 1252 Dasman </br> Postal Code: 15463 kuwait </br> KUWAIT</p>

{#														<p>Tel: <a href="tel:2123469333">212-346-9333</a></p>#}
													</div>

													<div class="row_block">
														<p><span class="add_title">Business inquiries:</span>
</br>

Please feel free to contact our business team:
</br>
<a href="mailto:bd@CallnMail.com"> bd@CallnMail.com </a>

														</p>
													</div>
												</div>
											</div>
										</div>
									</div>
								</div><!-- /contact_us -->

							</div>
						</div><!-- /content -->

						<div class="col-sm-4 col-md-3">
							{% include 'sidebar.html' %}
						</div><!-- /sidebar -->
					</div>
				</div>
			</div>
		</section>

{% endblock %}

callmail_project/templates/faq.html
{% extends 'base.html' %}
{% block head_content %}
<div class="height_100"></div>
{% endblock head_content %}
{% block content %}
<section id="main_content" class="bg_gray">
    <div class="container">
        <div class="sec_up">
            <div class="row alter">
                <div class="col-sm-8 col-md-9">
                    <div class="content">
                        <div class="about_us">
                            <div class="page_title">
                                <h1>FAQ</h1>
<p>CallnMail Frequently asked Question (FAQs)</p>


                            </div>
                            <!-- /page_title -->

                            <div class="row_block">
                                <h3>What is CallnMail?</h3>

                                <p>CallnMail is an email forwarding facility, acting through two channels: a website on the

internet, as well as providing its services through mobile applications.</p>
                            </div>

                            <div class="row_block">
                                <h3>Why use CallnMail?</h3>

                                <p>If you are using a mobile phone, you can register it with the CallnMail.com service in

order for other users and friends to be able to email you, without knowing your personal

or professional email ID.

In addition, when people are contacting you by phone, you can give out your email ID as

the CallnMail.com email.

Using the CallnMail.com services, you can find out your friends email ID, without

necessary knowing their personal email address.</p>
                            </div>

                            <div class="row_block">
                                <h3>Will I receive spam SMS or email?</h3>

                                <p>We provide restricted access of our users’ data, for advertising purposes and to legal

bodies, without discoursing the critical and sensitive user’s data like age, surname,

photos etc. Advertising companies may contact you or SMS you under a certain criteria

like, country, city, sex or age range, provided by CallnMail, according to terms of use.
                             We are trying hard to prevent our users from receiving SPAM email and SMS.
                                </p>
                            </div>







                             <div class="row_block">
                                <h3>What do you do for my security?</h3>

                                <p>We take our customer’s security very seriously.
                                </p>
                            </div>







                               <div class="row_block">
                                <h3>Is CallnMail FREE?</h3>

                                <p>Yes basic use of CallnMail is FREE, CallnMail App is free to download.
                                </p>
                            </div>



                               <div class="row_block">
                                <h3>How do I verify my email and mobile number?</h3>

                                <p>During the registration step, simply click on get the activation code, and an SMS will be

sent to your mobile number and you will be prompted to add on the website/app the

activation code you received.
                                </p>
                            </div>





                             <div class="row_block">
                                <h3>Do you provide a mailbox?</h3>

                                <p>No currently, we do not provide a mailbox and we are not an email provider. But we are

working on it.
                                </p>
                            </div>

                             <div class="row_block">
                                <h3>I have changed my number or someone else registered my number</h3>

                                <p>You can report to us any improper use of your personal mobile number by submitting a

form on our website and our team will correct any improper use or number correction.
                                </p>
                            </div>

                             <div class="row_block">
                                <h3>Changes to this Policy</h3>

                                <p>If we change our Policy, we will post the changes on this page. Please check the website

regularly for any changes to this Policy.
                                </p>
                            </div>



                        </div>
                    </div>
                </div>
                <!-- /content -->

                <div class="col-sm-4 col-md-3">
                    {% include 'sidebar.html' %}
                </div>
                <!-- /sidebar -->
            </div>
        </div>
    </div>
</section>
{% endblock %}

callmail_project/templates/mail_detail.html
{% extends "base.html" %}
{% block content %}
    <h4 class="text-success">Date: {{ mail.date_email }}</h4><br />
    <table class="table">
        <tr>
            <td><b>Mail From:</b> {{ mail.from_user }}</td>
        </tr>
        <tr>
            <td><b>Subject:</b> {{ mail.subject }}</td>
        </tr>
        <tr>
            <td><b>Body:</b> {% if mail.body %}<p><br />{{ mail.body }}</p>{% endif %}</td>
        </tr>
        <tr>
            <td><b>Attachments:</b>{% for attachment in mail.mailattachment_set.all %}<a href="{% url 'mail:download_attachment' attachment.pk %}">{{ attachment.filename }}</a> | {% endfor %}</td>
        </tr>

    </table>

{% endblock content %}

callmail_project/templates/mail_forward_list.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <section id="main_content" class="sec_profile">
			<div class="container">
				<div class="box_container">
						<div class="row">
							<div class="col-md-4 col-sm-5">
                            {% include 'profile_part.html' %}
							</div><!-- /p_content -->
							<div class="col-md-8 col-sm-7">
								<div class="create_new_link">
									<div class="p_content sec_half_left">
										<ul class="email_list">
                                        {% for mail in emails %}
											<li><input type="text" name="myhotmail" id="myhotmail{{ forloop.counter }}" placeholder="{{ mail.title }}" readonly/>
                                                <a href="{% url 'mail:mailforward_delete' mail.pk %}">x</a> <a href="{% url 'mail:mailforward_edit' mail.pk %}"> > </a> </li>
                                            {% endfor %}
										</ul>
										<div class="create_link">
											<a href="{% url 'mail:mailforward_create' %}"><i class="fa fa-plus"></i> Link new email address</a>
										</div>
									</div><!-- /p_content -->

									<div class="p_content sec_half_right">
										<div class="edit_panel">
											<a class="button" href="{% url 'mail:profile' %}">My Profile</a>
										</div>
									</div><!-- /p_content -->
								</div><!-- /change_pass -->
							</div>
						</div>
				</div>

				<div class="row">
					<div class="col-sm-12">
						<div class="app_store">
							<a href="https://itunes.apple.com/au/app/callnmail/id1023138715?mt=8"><img src="{% static 'images/icon_app_store.png' %}" alt="app_store"></a>
							<a href="https://play.google.com/store/apps/details?id=com.callnmail&hl=en"><img src="{% static 'images/icon_app_google_play.png' %}" alt="google_play"></a>
						</div>
					</div>
				</div>
			</div>
		</section>
{% endblock content %}

callmail_project/templates/mail_list.html
{% extends "base.html" %}

{% block content %}
        <h3 class="text-success">Mails</h3><br />
    <table class="table">
        {% if mails %}
        <tr>
            <td>Sender</td>
            <td>Subject</td>
            <td>Date</td>
        </tr>
        {% for mail in mails %}
        <tr>
            <td><a href="{% url 'mail:mail_detail' mail.pk %}">{{ mail.from_user }}</a></td>
            <td>{{ mail.subject }}</td>
            <td>{{ mail.date_email }}</td></a>
        </tr>
        {% endfor %}
        {% endif %}
    </table>
{% endblock content %}

callmail_project/templates/password_reset_form.html
{% extends 'base.html' %}
{% load static %}
{% block extra_css %}
	<link rel="stylesheet" type="text/css" href="{% static 'css/fuzzyDropdown.css' %}">
{% endblock extra_css %}
{% block extra_js %}
<script type="text/javascript" src="{% static 'js/fuse.min.js' %}"></script>
	<script type="text/javascript" src="{% static 'js/fuzzyDropdown.js' %}"></script>
{% endblock extra_js %}
{% block content %}
    <section id="main_content" class="registration bg_gray">
			<div class="container">
				<div class="page_title">
					<h1>Create an account or sign in</h1>
					<p>Use your phone number for the email address <br>and link it to your existing email.</p>
				</div><!-- /page_title -->
			</div>

			<div class="sec_reg">
				<div class="container">
					<div class="row">
						<div class="col-sm-12">
							<div class="tab_panel" role="tabpanel">
								<ul class="nav nav-tabs" role="tablist">
									<li role="presentation" class="active"><a href="#forget_password" aria-controls="forget_password" role="tab" data-toggle="tab">Forget Password</a></li>
								</ul>

								<div class="box_container">
									<div class="tab-content">
										<div role="tabpanel" class="tab-pane active" id="forget_password">
											<div class="tab_item_content active_account">
												<div class="content_logo"><a href="#"><img src="{% static 'images/content_logo_bg.png' %}" alt="logo"></a></div>

												<div class="reg_content">
                                                    <p class="text-warning">{{ form.non_field_errors }}</p>
													<form action="" method="post">
                                                        {% csrf_token %}

                                                        <div class="form-group">
															<div class="password">
                                                                {{ form.new_password1 }}
																<a class="input_add_on" href="#"><i class="fa fa-lock"></i></a>
                                                                <p class="text-warning">{{ form.new_password1.errors }}</p>
															</div>
														</div>
                                                        <div class="form-group">
															<div class="password">
                                                                {{ form.new_password2 }}
																<a class="input_add_on" href="#"><i class="fa fa-lock"></i></a>
                                                                <p class="text-warning">{{ form.new_password2.errors }}</p>
															</div>
														</div>
														<button type="submit" class="button">Reset Password</button>
													</form>
                                                    <br /> <br />
{#                                                    <i>If you don't have secret token <a href="{% url 'mail:reset_password_request' %}" style="color: firebrick;">click here</a></i>#}

												</div><!-- /reg_content -->
											</div>
										</div><!-- /tab_item_content -->
									</div>

									<span class="reg_ribbon"><img src="{% static 'images/ribbon.png' %}" alt="ribbon"></span>
									<span class="iphone_6"><img src="{% static 'images/iphone_6.png' %}" alt="iphone-6"></span>
								</div><!-- /box_container -->
							</div>
						</div>
					</div><!-- /row -->

					<div class="row">

						<div class="col-sm-12">
							<div class="app_store">
								<a href="https://itunes.apple.com/au/app/callnmail/id1023138715?mt=8"><img src="{% static 'images/icon_app_store.png' %}" alt="app_store"></a>
								<a href="https://play.google.com/store/apps/details?id=com.callnmail&hl=en"><img src="{% static 'images/icon_app_google_play.png' %}" alt="google_play"></a>
							</div>
						</div>
					</div><!-- /row -->
				</div>
			</div>
		</section>
{% endblock content %}

callmail_project/templates/test.html
{% load country_tags %}

{% block content %}



{% for object in codes %}
																    <option class="country" value="{{ object.prefix_val }}" data-country-code="{{ object.code|lower }}">
																	<div class="flag">
																            <div class="iti-flag {{ object.code|lower }}"></div>
																        </div>
																        <span class="dial-code">{{ object.prefix }}</span>
																        <span class="country-name">{{ object.name }}</span>

																	</option>
                                                                        {% endfor %}

{% endblock content %}